title: IPEF Investor Forum
url: https://ipefinvestorforum.org
favicon: /images/image001.jpg
colors:
  primary-color: "#8d6f57"
  secondary-color: "#d9b061"
  media-colors:
    - title: media-color-one
      color: "#28221e"
    - title: media-color-two
      color: "#8d6f57"
    - title: media-color-three
      color: "#d9b061"
    - title: media-color-four
      color: "#d9aa90"
    - title: media-color-five
      color: "#3f0d0c"
description: IPEF Investor Forum 2024
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.d2hbhu44qlvo7j.amplifyapp.com
prod: https://master.d14fuxh5d5qqhp.amplifyapp.com
facebook-pixel: ""
shareicon: /images/isomer-logo.svg
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
resources_name: media-centre
